### ISSUE TITLE
Beneficiary List

### ISSUE THREAD

**Issue by jevdiego** [luno/luno-go#17]
Hi,

I see the Luno API documentation changelog shows:

"2015-07-29: Added Perm_R_Beneficiaries and Perm_W_Beneficiaries permissions. You will have to generate a new API key if you require these permissions."

These permissions seem to be created for viewing, creating, and deleting beneficiaries

"Perm_R_Beneficiaries = 32768 (View beneficiaries)
Perm_W_Beneficiaries = 65536 (Create and delete beneficiaries)"

I don't see any APIs to actually do this though? Do they exist? And if so, does this library support them?

Thanks,

**Comment by neilgarb** [comment]
@jevdiego The permissions are required for some undocumented API endpoints. We use those endpoints internally, and they are not supported in our client SDKs. Apologies for the confusion.

**Comment by neilgarb** [comment]
@jevdiego Not at this point. Are you able to share your use-case?

**Comment by neilgarb** [comment]
@jevdiego Please feel free to mail support@luno.com
