### ISSUE TITLE
listtrades API - Receiving no trades

### ISSUE THREAD

**Issue by jevdiego** [luno/luno-go#24]
Hi,

I'm currently receiving no trades when I request them. This previously has worked though :/
I definitely have trades on this account, so under what condition should I be expecting 'null' for the trades? 

`
let auth = new Buffer(API_KEY + ':' + API_SECRET).toString('base64');
request({
            url: 'https://api.mybitx.com/api/1/listtrades?pair=XBTZAR',
            method: 'GET',
            headers: {
                Authorization: 'Basic ' + auth,
                'Content-Type': 'application/json',
            },
        }, function (error, response, body) {

            if (error) {
                return reject('[getLunoTrades] ' + error);
            }

            if (!response) {
                return reject('[getLunoTrades] Response is ' + response);
            }

            if (response.statusCode >= 400) {
                return reject('[getLunoTrades] Error ' + response.error);
            }

            let jsonTrades = JSON.parse(response.body);
            console.log(jsonTrades);
            if (jsonTrades.trades != null) {
                return resolve(jsonTrades.trades);
            } else {
                return resolve([]);
            }
        });
`

Console output:
`
{ trades: null }
`

**Comment by jevdiego** [comment]
Apologies about the styling above, can't seem to get that code to display correctly.

**Comment by neilgarb** [comment]
@jevdiego This should now be resolved. The issue was caused by a bug.

**Comment by jevdiego** [comment]
Thanks @neilgarb for the prompt feedback. Tested my side too and working 100%
