### ISSUE TITLE
No way to add callbacks to streaming Conn

### ISSUE THREAD

**Issue by jacoduplessis** [luno/luno-go#30]
I might be missing something obvious but I don't see a way of adding a callback to the Conn struct in the streaming package.

The two fields `connectCallback` and `updateCallback` on the struct are lowercase and therefore cannot be set from outside the package.

Would it be possible to create a way of adding callbacks to the Conn? Either by exporting the struct fields or creating a new factory function that accepts callbacks.

**Comment by neilgarb** [comment]
@jacoduplessis Please see https://github.com/luno/luno-go/blob/master/examples/stream/main.go for an example of passing a callback into Dial(). You can pass an update callback in in a similar way.

**Comment by jacoduplessis** [comment]
Indeed, I was missing the obvious. Thanks!
