### ISSUE TITLE
ETH Withdrawal

### ISSUE THREAD

**Issue by jevdiego** [luno/luno-go#35]
Hi,

I've noticed an issue with ETH withdrawals lately. This has happened a few times on our corporate account. This is actually not a API wrapper issue, but I'm not sure what the right forum to raise this would be.

![image](https://user-images.githubusercontent.com/20283397/65828432-2d571200-e29b-11e9-8504-b9bceca1f688.png)

Above shows an ETH withdrawal from yesterday. However, this is still in this state. I have to login, click 'STOP' and re-submit our withdrawal. This initial ETH transfer seems to have never been submitted.

I expect that we could implement a workaround, and cancel the withdrawal after X period and then submit, but obviously I'd rather not have to go this route.

**Comment by neilgarb** [comment]
@jevdiego Thanks for the submitting this issue. Unfortunately this repo isn't monitored very frequently. Please submit this issue to our support team (support@luno.com) if you haven't already. It'll get routed to the right team.
