### ISSUE TITLE
Combined order book volumes

### ISSUE THREAD

**Issue by JasonTribe** [luno/luno-go#50]
Hi, is there any way to return the combined order book entries where the volumes of asks/bids with the same price are summed together? Or does this have to be done by the calling app when an update is received?

**Comment by adamhicks** [comment]
Hey @JasonTribe at the moment you get the breakdown for each Order but actually I can see that this isn't really how it should be. I think this is a bug, the orders should be condensed and we'll fix asap.

**Comment by neilgarb** [comment]
@adamhicks worried about a BC break. How about adding a parameter?

**Comment by adamhicks** [comment]
#51 created
this would hide the breakdown for any client relying on an order book entry for each actual order.

**Comment by JasonTribe** [comment]
Awesome, thanks guys!
