### ISSUE TITLE
Get highest and lowest prices of exchanges in the last 24 hours

### ISSUE THREAD

**Issue by kompleksanda** [luno/luno-go#55]
Hi.

Is there a way I can return the highest and the lowest prices of exchange pairs in the last 24 hours, or a week, or a year?
Thanks.

**Comment by AnthonyLombard** [comment]
From what I can see you would need to pull the candle data for those time frames using the LUNO docs (As of right now the candle endpoint is waiting for review) and extrapolate yourself using a loop.

**Comment by neilgarb** [comment]
Thanks @AnthonyLombard. @kompleksanda I'm in the process of updating our SDKs to add the candles endpoint.

**Comment by kompleksanda** [comment]
@AnthonyLombard thanks. @neilgarb when you do please let me know. Thank you!

**Comment by neilgarb** [comment]
@kompleksanda I've created release v0.0.26.
