### ISSUE TITLE
Wrong "type" values documented for GetOrder endpoint

### ISSUE THREAD

**Issue by matiboy** [luno/luno-go#65]
Both the [documentation](https://www.luno.com/en/developers/api#operation/GetOrder) and the code here show OrderType (type) as "BID" or "ASK" for the GetOrder endpoint, however the response contains "SELL" or "BUY"

```json
{
    "base": "1.0263",
    "completed_timestamp": 1621595283273,
    "counter": "3599.2341",
    "creation_timestamp": 1621595283238,
    "expiration_timestamp": 0,
    "fee_base": "0.0030789",
    "fee_counter": "0.00",
    "limit_price": "0.00",
    "limit_volume": "1.0263",
    "order_id": "SOMEID",
    "pair": "BCHMYR",
    "state": "COMPLETE",
    "trades": [
        {
            "is_buy": false,
            "price": "3507.00",
            "sequence": 135867,
            "timestamp": 1621595283273,
            "volume": "0.4555"
        },
        {
            "is_buy": false,
            "price": "3507.00",
            "sequence": 135868,
            "timestamp": 1621595283273,
            "volume": "0.5708"
        }
    ],
    "type": "SELL"
}

```

**Comment by adamhicks** [comment]
Hi there, cheers, we'll look into this.

**Comment by remiroz** [comment]
The doc has been updated: it's BUY and SELL for market orders.
We also have Get Order v2 and advise to use that one.

**Comment by matiboy** [comment]
Thank you both

@remiroz noted on the suggestion to use v2 (even v3?). The reason why that's not currently possible in my case is because I use [ccxt](https://github.com/ccxt/ccxt/issues) and they use v1.

One more question if you don't mind @adamhicks : is this repo a good place to ask questions/feature requests related to the API itself - not necessarily the Go client, and if not, do you know where would be the right place? For example, would be nice if market orders can take `base_volume` even for `BUY` order.

Thanks!
