### ISSUE TITLE
Contacting support Luno Websocket API

### ISSUE THREAD

**Issue by lathanbritz** [luno/luno-go#88]
Hey there can you help point me in the direction to get in contact with someone that works with the Luno Websocket API.

Based on the sockets available and information they provide on the support page im unable to rebuild the order book. Would much appreciate any help.

If this issue should live in one of the other repos here at Luno, please point me in the right direction.

Thanks!

**Comment by adamhicks** [comment]
Hey there! Glad to hear you're making use of the Websocket API. Are you using the client implementation in this luno-go repo or are you building your own based on the documentation [here](https://www.luno.com/en/developers/api#tag/Streaming-API)?

**Comment by lathanbritz** [comment]
my own baised on the documentation and looking at a few other implementations im building against javascript. And validated my algo rhythm in line with the documentation and this implementation in python https://github.com/jacoduplessis/luno_streams/blob/master/luno_streams/updater.py

the sequence numbers line up for me, I add and remove item like they do here key'ed by id, etc. etc... but letting it run I relatively fast endup with a book way out of sync.

So was looking to catch someone that maybe I could possible find out what is off. Know this is all around go here but I could not find any repo dedicated to the websockets.... or javascript so I dropped a line here.

**Comment by lathanbritz** [comment]
figured it out petty there no websocket repo to ask these questions would be a nice +1.
also a place to ask for features. eg, a crc32 sum check on the order books to make 100% sure you have a valid copy.
